/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author Camille
 */
public class testFenetre extends javax.swing.JFrame {

    /**
     * Creates new form testFenetre
     */
    public testFenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        paneHome = new javax.swing.JPanel();
        cursusTextHome = new javax.swing.JTextField();
        edtTextHome = new javax.swing.JTextField();
        dateHome = new javax.swing.JSpinner();
        iconeHome = new javax.swing.JButton();
        scrollPaneHome = new javax.swing.JScrollPane();
        tabCoursHome = new javax.swing.JTable();
        coursPan = new javax.swing.JPanel();
        tabbedPaneCours = new javax.swing.JTabbedPane();
        edtPan = new javax.swing.JPanel();
        paneCours = new javax.swing.JPanel();
        vueEdt = new javax.swing.JComboBox<>();
        rechercheCours = new javax.swing.JComboBox<>();
        rechercheBarreCours = new javax.swing.JTextField();
        rechercheBoutonCours = new javax.swing.JButton();
        semaineCours = new javax.swing.JComboBox<>();
        scrollPaneCours = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCours = new javax.swing.JTable();
        recapCoursPan = new javax.swing.JPanel();
        scrollPaneRecapCours = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabRecapCours = new javax.swing.JTable();
        panSalles = new javax.swing.JTabbedPane();
        edtPan1 = new javax.swing.JPanel();
        paneSalle = new javax.swing.JPanel();
        vueSalle = new javax.swing.JComboBox<>();
        rechercheSalle = new javax.swing.JComboBox<>();
        rechercheBarreSalle = new javax.swing.JTextField();
        rechercheBoutonSalle = new javax.swing.JButton();
        semaineSalle = new javax.swing.JComboBox<>();
        scrollPaneSalle = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabSalle = new javax.swing.JTable();
        recapCoursPan1 = new javax.swing.JPanel();
        scrollPaneRecapSalle = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabLibresSalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planning, [Année scolaire] - [icone] [NOM Prénom] (ECE Paris [Promo])");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(30, 0, 0, 0));
        setName("fenetre"); // NOI18N

        cursusTextHome.setEditable(false);
        cursusTextHome.setBackground(new java.awt.Color(255, 255, 255));
        cursusTextHome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cursusTextHome.setText("Mon cursus");
        cursusTextHome.setBorder(null);
        cursusTextHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursusTextHomeActionPerformed(evt);
            }
        });

        edtTextHome.setText("Emploi du temps");
        edtTextHome.setBorder(null);
        edtTextHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTextHomeActionPerformed(evt);
            }
        });

        dateHome.setModel(new javax.swing.SpinnerDateModel());
        dateHome.setBorder(null);

        iconeHome.setText("Icon");

        scrollPaneHome.setBackground(new java.awt.Color(204, 204, 204));
        scrollPaneHome.setForeground(new java.awt.Color(204, 204, 204));
        scrollPaneHome.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabCoursHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Horaires", "Cours"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneHome.setViewportView(tabCoursHome);

        javax.swing.GroupLayout paneHomeLayout = new javax.swing.GroupLayout(paneHome);
        paneHome.setLayout(paneHomeLayout);
        paneHomeLayout.setHorizontalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneHomeLayout.createSequentialGroup()
                        .addComponent(edtTextHome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateHome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconeHome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursusTextHome, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
        );
        paneHomeLayout.setVerticalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtTextHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconeHome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cursusTextHome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneHome, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Home", paneHome);

        vueEdt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en grille", "en liste" }));
        vueEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueEdtActionPerformed(evt);
            }
        });

        rechercheCours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[NOM Prénom]", "[NOM Prénom]", "[NOM Prénom]" }));

        rechercheBarreCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheBarreCoursActionPerformed(evt);
            }
        });

        rechercheBoutonCours.setText("Icon");

        semaineCours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semaine", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "..." }));

        tabCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Horaires", "[Date]", "[Date]", "[Date]", "[Date]", "[Date]", "[Date]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCours.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabCours);

        scrollPaneCours.setViewportView(jScrollPane1);

        javax.swing.GroupLayout paneCoursLayout = new javax.swing.GroupLayout(paneCours);
        paneCours.setLayout(paneCoursLayout);
        paneCoursLayout.setHorizontalGroup(
            paneCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCoursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneCours)
                    .addGroup(paneCoursLayout.createSequentialGroup()
                        .addComponent(vueEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheCours, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheBarreCours, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheBoutonCours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(semaineCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneCoursLayout.setVerticalGroup(
            paneCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCoursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vueEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheBarreCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheBoutonCours)
                    .addComponent(semaineCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneCours, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout edtPanLayout = new javax.swing.GroupLayout(edtPan);
        edtPan.setLayout(edtPanLayout);
        edtPanLayout.setHorizontalGroup(
            edtPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        edtPanLayout.setVerticalGroup(
            edtPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPaneCours.addTab("Emploi du temps", edtPan);

        scrollPaneRecapCours.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabRecapCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matière", "Première séance", "Dernière séance", "Durée", "Nb."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabRecapCours);
        if (tabRecapCours.getColumnModel().getColumnCount() > 0) {
            tabRecapCours.getColumnModel().getColumn(2).setHeaderValue("Dernière séance");
        }

        scrollPaneRecapCours.setViewportView(jScrollPane3);

        javax.swing.GroupLayout recapCoursPanLayout = new javax.swing.GroupLayout(recapCoursPan);
        recapCoursPan.setLayout(recapCoursPanLayout);
        recapCoursPanLayout.setHorizontalGroup(
            recapCoursPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneRecapCours, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        recapCoursPanLayout.setVerticalGroup(
            recapCoursPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneRecapCours)
        );

        tabbedPaneCours.addTab("Récapitulatif des cours", recapCoursPan);

        javax.swing.GroupLayout coursPanLayout = new javax.swing.GroupLayout(coursPan);
        coursPan.setLayout(coursPanLayout);
        coursPanLayout.setHorizontalGroup(
            coursPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCours)
        );
        coursPanLayout.setVerticalGroup(
            coursPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCours)
        );

        tabbedPane.addTab("Cours", coursPan);

        vueSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en grille", "en liste" }));
        vueSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueSalleActionPerformed(evt);
            }
        });

        rechercheSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Bat. N°]", "[Bat. N°]", "[Bat. N°]" }));

        rechercheBarreSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheBarreSalleActionPerformed(evt);
            }
        });

        rechercheBoutonSalle.setText("Icon");

        semaineSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semaine", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "..." }));

        tabSalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Horaires", "[Date]", "[Date]", "[Date]", "[Date]", "[Date]", "[Date]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabSalle.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tabSalle);

        scrollPaneSalle.setViewportView(jScrollPane4);

        javax.swing.GroupLayout paneSalleLayout = new javax.swing.GroupLayout(paneSalle);
        paneSalle.setLayout(paneSalleLayout);
        paneSalleLayout.setHorizontalGroup(
            paneSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneSalle)
                    .addGroup(paneSalleLayout.createSequentialGroup()
                        .addComponent(vueSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheBarreSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheBoutonSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(semaineSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneSalleLayout.setVerticalGroup(
            paneSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vueSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheBarreSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheBoutonSalle)
                    .addComponent(semaineSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout edtPan1Layout = new javax.swing.GroupLayout(edtPan1);
        edtPan1.setLayout(edtPan1Layout);
        edtPan1Layout.setHorizontalGroup(
            edtPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneSalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        edtPan1Layout.setVerticalGroup(
            edtPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edtPan1Layout.createSequentialGroup()
                .addComponent(paneSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panSalles.addTab("Emploi du temps", edtPan1);

        scrollPaneRecapSalle.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabLibresSalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Site", "Date", "Durée", "Capacité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabLibresSalle);

        scrollPaneRecapSalle.setViewportView(jScrollPane5);

        javax.swing.GroupLayout recapCoursPan1Layout = new javax.swing.GroupLayout(recapCoursPan1);
        recapCoursPan1.setLayout(recapCoursPan1Layout);
        recapCoursPan1Layout.setHorizontalGroup(
            recapCoursPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneRecapSalle, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        recapCoursPan1Layout.setVerticalGroup(
            recapCoursPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneRecapSalle)
        );

        panSalles.addTab("Salles libres", recapCoursPan1);

        tabbedPane.addTab("Salles", panSalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheBarreSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheBarreSalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheBarreSalleActionPerformed

    private void vueSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueSalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vueSalleActionPerformed

    private void rechercheBarreCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheBarreCoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheBarreCoursActionPerformed

    private void vueEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vueEdtActionPerformed

    private void edtTextHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTextHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTextHomeActionPerformed

    private void cursusTextHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursusTextHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursusTextHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testFenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coursPan;
    private javax.swing.JTextField cursusTextHome;
    private javax.swing.JSpinner dateHome;
    private javax.swing.JPanel edtPan;
    private javax.swing.JPanel edtPan1;
    private javax.swing.JTextField edtTextHome;
    private javax.swing.JButton iconeHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane panSalles;
    private javax.swing.JPanel paneCours;
    private javax.swing.JPanel paneHome;
    private javax.swing.JPanel paneSalle;
    private javax.swing.JPanel recapCoursPan;
    private javax.swing.JPanel recapCoursPan1;
    private javax.swing.JTextField rechercheBarreCours;
    private javax.swing.JTextField rechercheBarreSalle;
    private javax.swing.JButton rechercheBoutonCours;
    private javax.swing.JButton rechercheBoutonSalle;
    private javax.swing.JComboBox<String> rechercheCours;
    private javax.swing.JComboBox<String> rechercheSalle;
    private javax.swing.JScrollPane scrollPaneCours;
    private javax.swing.JScrollPane scrollPaneHome;
    private javax.swing.JScrollPane scrollPaneRecapCours;
    private javax.swing.JScrollPane scrollPaneRecapSalle;
    private javax.swing.JScrollPane scrollPaneSalle;
    private javax.swing.JComboBox<String> semaineCours;
    private javax.swing.JComboBox<String> semaineSalle;
    private javax.swing.JTable tabCours;
    private javax.swing.JTable tabCoursHome;
    private javax.swing.JTable tabLibresSalle;
    private javax.swing.JTable tabRecapCours;
    private javax.swing.JTable tabSalle;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTabbedPane tabbedPaneCours;
    private javax.swing.JComboBox<String> vueEdt;
    private javax.swing.JComboBox<String> vueSalle;
    // End of variables declaration//GEN-END:variables
}
