/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author Camille
 */
public class testSP extends javax.swing.JPanel {

    /**
     * Creates new form testSP
     */
    public testSP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeDroitSP = new javax.swing.ButtonGroup();
        groupeDroitModifSP = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabbedPaneServicePlanification = new javax.swing.JTabbedPane();
        paneGererUtilisateursSP = new javax.swing.JScrollPane();
        containerSP = new javax.swing.JPanel();
        splitGererUtilisateursSP = new javax.swing.JSplitPane();
        paneListeSP = new javax.swing.JPanel();
        scrollListeSP = new javax.swing.JScrollPane();
        listeUtilisateursSP = new javax.swing.JList<>();
        paneGererSP = new javax.swing.JPanel();
        paneModificationSP = new javax.swing.JPanel();
        emailSP = new javax.swing.JLabel();
        nomSP = new javax.swing.JLabel();
        prenomSP = new javax.swing.JLabel();
        droitSP = new javax.swing.JLabel();
        referentSP = new javax.swing.JRadioButton();
        enseignantSP = new javax.swing.JRadioButton();
        etudiantSP = new javax.swing.JRadioButton();
        numeroSP = new javax.swing.JLabel();
        modifierTextSP = new javax.swing.JLabel();
        boutonSupp = new javax.swing.JButton();
        selectionProfilSP = new javax.swing.JComboBox<>();
        paneModificationSP2 = new javax.swing.JPanel();
        emailTextSP = new javax.swing.JLabel();
        nomTextSP = new javax.swing.JLabel();
        prenomTextSP = new javax.swing.JLabel();
        droitTextSP = new javax.swing.JLabel();
        referentAddSP = new javax.swing.JRadioButton();
        enseignantAddSP = new javax.swing.JRadioButton();
        etudiantAddSP = new javax.swing.JRadioButton();
        emailAddSP = new javax.swing.JTextField();
        nomAddSP = new javax.swing.JTextField();
        prenomAddSP1 = new javax.swing.JTextField();
        validerSP = new javax.swing.JButton();
        ajouterTextSP = new javax.swing.JLabel();

        paneGererUtilisateursSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        splitGererUtilisateursSP.setResizeWeight(0.5);
        splitGererUtilisateursSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        splitGererUtilisateursSP.setOneTouchExpandable(true);

        listeUtilisateursSP.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeUtilisateursSP.setAutoscrolls(false);
        scrollListeSP.setViewportView(listeUtilisateursSP);

        javax.swing.GroupLayout paneListeSPLayout = new javax.swing.GroupLayout(paneListeSP);
        paneListeSP.setLayout(paneListeSPLayout);
        paneListeSPLayout.setHorizontalGroup(
            paneListeSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollListeSP, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        paneListeSPLayout.setVerticalGroup(
            paneListeSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListeSPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scrollListeSP, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        splitGererUtilisateursSP.setRightComponent(paneListeSP);
        paneListeSP.getAccessibleContext().setAccessibleName("");

        emailSP.setText("Adresse mail :        [email]");

        nomSP.setText("Nom :                     [NOM]");

        prenomSP.setText("Prénom :                [Prénom]");

        droitSP.setText("Droit d'accès :");

        groupeDroitSP.add(referentSP);
        referentSP.setText("Référent pédagogique");

        groupeDroitSP.add(enseignantSP);
        enseignantSP.setText("Enseignant");

        groupeDroitSP.add(etudiantSP);
        etudiantSP.setText("Etudiant");

        numeroSP.setText("Numéro étudiant : [numéro]");

        modifierTextSP.setText("Modifier les utilisateurs");

        boutonSupp.setText("Supprimer");
        boutonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSuppActionPerformed(evt);
            }
        });

        selectionProfilSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veuillez sélectionner", "Référent", "Enseignant", "Etudiant" }));
        selectionProfilSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionProfilSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneModificationSPLayout = new javax.swing.GroupLayout(paneModificationSP);
        paneModificationSP.setLayout(paneModificationSPLayout);
        paneModificationSPLayout.setHorizontalGroup(
            paneModificationSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificationSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneModificationSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneModificationSPLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(boutonSupp))
                    .addGroup(paneModificationSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(prenomSP, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(nomSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneModificationSPLayout.createSequentialGroup()
                        .addComponent(droitSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(referentSP)
                        .addGap(0, 0, 0)
                        .addComponent(enseignantSP)
                        .addGap(0, 0, 0)
                        .addComponent(etudiantSP))
                    .addComponent(numeroSP, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierTextSP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectionProfilSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        paneModificationSPLayout.setVerticalGroup(
            paneModificationSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificationSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modifierTextSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionProfilSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailSP)
                .addGap(13, 13, 13)
                .addComponent(nomSP)
                .addGap(13, 13, 13)
                .addComponent(prenomSP)
                .addGap(13, 13, 13)
                .addComponent(numeroSP)
                .addGap(13, 13, 13)
                .addGroup(paneModificationSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(droitSP)
                    .addComponent(referentSP)
                    .addComponent(enseignantSP)
                    .addComponent(etudiantSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonSupp)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        emailTextSP.setText("Adresse mail :");

        nomTextSP.setText("Nom :");

        prenomTextSP.setText("Prénom :");

        droitTextSP.setText("Droit d'accès :");

        groupeDroitModifSP.add(referentAddSP);
        referentAddSP.setText("Référent pédagogique");
        referentAddSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referentAddSPActionPerformed(evt);
            }
        });

        groupeDroitModifSP.add(enseignantAddSP);
        enseignantAddSP.setText("Enseignant");

        groupeDroitModifSP.add(etudiantAddSP);
        etudiantAddSP.setText("Etudiant");

        emailAddSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddSPActionPerformed(evt);
            }
        });

        validerSP.setText("Valider");

        ajouterTextSP.setText("Ajouter un utilisateur");

        javax.swing.GroupLayout paneModificationSP2Layout = new javax.swing.GroupLayout(paneModificationSP2);
        paneModificationSP2.setLayout(paneModificationSP2Layout);
        paneModificationSP2Layout.setHorizontalGroup(
            paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificationSP2Layout.createSequentialGroup()
                .addGroup(paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(paneModificationSP2Layout.createSequentialGroup()
                            .addComponent(emailTextSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailAddSP))
                        .addGroup(paneModificationSP2Layout.createSequentialGroup()
                            .addComponent(nomTextSP)
                            .addGap(43, 43, 43)
                            .addComponent(nomAddSP))
                        .addGroup(paneModificationSP2Layout.createSequentialGroup()
                            .addComponent(prenomTextSP)
                            .addGap(28, 28, 28)
                            .addComponent(prenomAddSP1))
                        .addGroup(paneModificationSP2Layout.createSequentialGroup()
                            .addComponent(droitTextSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(referentAddSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enseignantAddSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(etudiantAddSP)))
                    .addComponent(ajouterTextSP))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(paneModificationSP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validerSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneModificationSP2Layout.setVerticalGroup(
            paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModificationSP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajouterTextSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextSP)
                    .addComponent(emailAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomTextSP)
                    .addComponent(nomAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomTextSP)
                    .addComponent(prenomAddSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(paneModificationSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(droitTextSP)
                    .addComponent(referentAddSP)
                    .addComponent(enseignantAddSP)
                    .addComponent(etudiantAddSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validerSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneGererSPLayout = new javax.swing.GroupLayout(paneGererSP);
        paneGererSP.setLayout(paneGererSPLayout);
        paneGererSPLayout.setHorizontalGroup(
            paneGererSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGererSPLayout.createSequentialGroup()
                .addComponent(paneModificationSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneGererSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneModificationSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneGererSPLayout.setVerticalGroup(
            paneGererSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGererSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneModificationSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneModificationSP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitGererUtilisateursSP.setLeftComponent(paneGererSP);

        javax.swing.GroupLayout containerSPLayout = new javax.swing.GroupLayout(containerSP);
        containerSP.setLayout(containerSPLayout);
        containerSPLayout.setHorizontalGroup(
            containerSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerSPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(splitGererUtilisateursSP)
                .addGap(0, 0, 0))
        );
        containerSPLayout.setVerticalGroup(
            containerSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerSPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(splitGererUtilisateursSP, javax.swing.GroupLayout.PREFERRED_SIZE, 422, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        paneGererUtilisateursSP.setViewportView(containerSP);

        tabbedPaneServicePlanification.addTab("Gérer les utilisateurs", paneGererUtilisateursSP);

        jTabbedPane1.addTab("tab1", tabbedPaneServicePlanification);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectionProfilSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionProfilSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectionProfilSPActionPerformed

    private void boutonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonSuppActionPerformed

    private void emailAddSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddSPActionPerformed

    private void referentAddSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referentAddSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referentAddSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajouterTextSP;
    private javax.swing.JButton boutonSupp;
    private javax.swing.JPanel containerSP;
    private javax.swing.JLabel droitSP;
    private javax.swing.JLabel droitTextSP;
    private javax.swing.JTextField emailAddSP;
    private javax.swing.JLabel emailSP;
    private javax.swing.JLabel emailTextSP;
    private javax.swing.JRadioButton enseignantAddSP;
    private javax.swing.JRadioButton enseignantSP;
    private javax.swing.JRadioButton etudiantAddSP;
    private javax.swing.JRadioButton etudiantSP;
    private javax.swing.ButtonGroup groupeDroitModifSP;
    private javax.swing.ButtonGroup groupeDroitSP;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listeUtilisateursSP;
    private javax.swing.JLabel modifierTextSP;
    private javax.swing.JTextField nomAddSP;
    private javax.swing.JLabel nomSP;
    private javax.swing.JLabel nomTextSP;
    private javax.swing.JLabel numeroSP;
    private javax.swing.JPanel paneGererSP;
    private javax.swing.JScrollPane paneGererUtilisateursSP;
    private javax.swing.JPanel paneListeSP;
    private javax.swing.JPanel paneModificationSP;
    private javax.swing.JPanel paneModificationSP2;
    private javax.swing.JTextField prenomAddSP1;
    private javax.swing.JLabel prenomSP;
    private javax.swing.JLabel prenomTextSP;
    private javax.swing.JRadioButton referentAddSP;
    private javax.swing.JRadioButton referentSP;
    private javax.swing.JScrollPane scrollListeSP;
    private javax.swing.JComboBox<String> selectionProfilSP;
    private javax.swing.JSplitPane splitGererUtilisateursSP;
    private javax.swing.JTabbedPane tabbedPaneServicePlanification;
    private javax.swing.JButton validerSP;
    // End of variables declaration//GEN-END:variables
}
