/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author Camille
 */
public class testSP extends javax.swing.JPanel {

    /**
     * Creates new form testSP
     */
    public testSP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeDroitSP = new javax.swing.ButtonGroup();
        groupeDroitModifSP = new javax.swing.ButtonGroup();
        groupeEtatSP = new javax.swing.ButtonGroup();
        groupeEtatModifSP = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabbedPaneServicePlanification = new javax.swing.JTabbedPane();
        paneGererCoursSP = new javax.swing.JSplitPane();
        paneGererSiteSP = new javax.swing.JPanel();
        paneSitesSP = new javax.swing.JPanel();
        siteSalleSP = new javax.swing.JLabel();
        selectionnerSiteSP = new javax.swing.JComboBox<>();
        paneListeSallesSP = new javax.swing.JScrollPane();
        listeSallesSP = new javax.swing.JList<>();
        salleSP = new javax.swing.JLabel();
        capaciteSP = new javax.swing.JLabel();
        siteSP = new javax.swing.JLabel();
        supprimerSalleSP = new javax.swing.JButton();
        supprimerSiteSP = new javax.swing.JButton();
        modifierCapaciteSP = new javax.swing.JButton();
        paneAjouterSiteSP = new javax.swing.JPanel();
        ajouterSiteSP = new javax.swing.JLabel();
        siteAddSP = new javax.swing.JLabel();
        siteTFSP = new javax.swing.JTextField();
        validerSiteSP = new javax.swing.JButton();
        paneAjouterSalleSP = new javax.swing.JPanel();
        ajouterSalleSP = new javax.swing.JLabel();
        salleAddSP = new javax.swing.JLabel();
        salleTFSP = new javax.swing.JTextField();
        validerSalleSP = new javax.swing.JButton();
        selectionnerSiteSP2 = new javax.swing.JComboBox<>();
        capaciteAddSP = new javax.swing.JLabel();
        capaciteSpinnerSP = new javax.swing.JSpinner();

        paneGererCoursSP.setResizeWeight(0.5);
        tabbedPaneServicePlanification.addTab("Gérer les cours", paneGererCoursSP);

        siteSalleSP.setText("Sites et salles :");

        selectionnerSiteSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Site", "Eiffel 1", "Eiffel 2", "Eiffel 3", "Eiffel 4", "Eiffel 5", "CNAM" }));

        listeSallesSP.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        paneListeSallesSP.setViewportView(listeSallesSP);

        salleSP.setText("Salle : [Salle]");

        capaciteSP.setText("Capacité : [Cap.]");

        siteSP.setText("Site : [Site]");

        supprimerSalleSP.setText("Supprimer");
        supprimerSalleSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerSalleSPActionPerformed(evt);
            }
        });

        supprimerSiteSP.setText("Supprimer");
        supprimerSiteSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerSiteSPActionPerformed(evt);
            }
        });

        modifierCapaciteSP.setText("Modifier");

        ajouterSiteSP.setText("Ajouter un site :");

        siteAddSP.setText("Site : ");

        validerSiteSP.setText("Valider");

        javax.swing.GroupLayout paneAjouterSiteSPLayout = new javax.swing.GroupLayout(paneAjouterSiteSP);
        paneAjouterSiteSP.setLayout(paneAjouterSiteSPLayout);
        paneAjouterSiteSPLayout.setHorizontalGroup(
            paneAjouterSiteSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAjouterSiteSPLayout.createSequentialGroup()
                .addComponent(ajouterSiteSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneAjouterSiteSPLayout.createSequentialGroup()
                .addComponent(siteAddSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siteTFSP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validerSiteSP, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
        );
        paneAjouterSiteSPLayout.setVerticalGroup(
            paneAjouterSiteSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAjouterSiteSPLayout.createSequentialGroup()
                .addComponent(ajouterSiteSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneAjouterSiteSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteAddSP)
                    .addComponent(siteTFSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerSiteSP))
                .addContainerGap())
        );

        ajouterSalleSP.setText("Ajouter une salle :");

        salleAddSP.setText("Salle :");

        validerSalleSP.setText("Valider");

        selectionnerSiteSP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Site", "Eiffel 1", "Eiffel 2", "Eiffel 3", "Eiffel 4", "Eiffel 5", "CNAM" }));

        capaciteAddSP.setText("Capacité :");

        javax.swing.GroupLayout paneAjouterSalleSPLayout = new javax.swing.GroupLayout(paneAjouterSalleSP);
        paneAjouterSalleSP.setLayout(paneAjouterSalleSPLayout);
        paneAjouterSalleSPLayout.setHorizontalGroup(
            paneAjouterSalleSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAjouterSalleSPLayout.createSequentialGroup()
                .addGroup(paneAjouterSalleSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajouterSalleSP)
                    .addComponent(selectionnerSiteSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneAjouterSalleSPLayout.createSequentialGroup()
                .addComponent(capaciteAddSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capaciteSpinnerSP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(validerSalleSP, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneAjouterSalleSPLayout.createSequentialGroup()
                .addComponent(salleAddSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salleTFSP, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneAjouterSalleSPLayout.setVerticalGroup(
            paneAjouterSalleSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAjouterSalleSPLayout.createSequentialGroup()
                .addComponent(ajouterSalleSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionnerSiteSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneAjouterSalleSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salleAddSP)
                    .addComponent(salleTFSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneAjouterSalleSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capaciteAddSP)
                    .addComponent(validerSalleSP)
                    .addComponent(capaciteSpinnerSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout paneSitesSPLayout = new javax.swing.GroupLayout(paneSitesSP);
        paneSitesSP.setLayout(paneSitesSPLayout);
        paneSitesSPLayout.setHorizontalGroup(
            paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSitesSPLayout.createSequentialGroup()
                .addComponent(siteSalleSP)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneSitesSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneListeSallesSP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectionnerSiteSP, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSitesSPLayout.createSequentialGroup()
                        .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salleSP)
                            .addComponent(capaciteSP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supprimerSalleSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifierCapaciteSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(paneSitesSPLayout.createSequentialGroup()
                        .addComponent(siteSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supprimerSiteSP))
                    .addComponent(paneAjouterSiteSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneAjouterSalleSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneSitesSPLayout.setVerticalGroup(
            paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSitesSPLayout.createSequentialGroup()
                .addComponent(siteSalleSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneSitesSPLayout.createSequentialGroup()
                        .addComponent(selectionnerSiteSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siteSP)
                            .addComponent(supprimerSiteSP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salleSP)
                            .addComponent(supprimerSalleSP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneSitesSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifierCapaciteSP)
                            .addComponent(capaciteSP))
                        .addGap(18, 18, 18)
                        .addComponent(paneAjouterSiteSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneAjouterSalleSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(paneListeSallesSP))
                .addContainerGap())
        );

        javax.swing.GroupLayout paneGererSiteSPLayout = new javax.swing.GroupLayout(paneGererSiteSP);
        paneGererSiteSP.setLayout(paneGererSiteSPLayout);
        paneGererSiteSPLayout.setHorizontalGroup(
            paneGererSiteSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGererSiteSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneSitesSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        paneGererSiteSPLayout.setVerticalGroup(
            paneGererSiteSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGererSiteSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneSitesSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneServicePlanification.addTab("Gérer le site", paneGererSiteSP);

        jTabbedPane1.addTab("tab1", tabbedPaneServicePlanification);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerSiteSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerSiteSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerSiteSPActionPerformed

    private void supprimerSalleSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerSalleSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerSalleSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajouterSalleSP;
    private javax.swing.JLabel ajouterSiteSP;
    private javax.swing.JLabel capaciteAddSP;
    private javax.swing.JLabel capaciteSP;
    private javax.swing.JSpinner capaciteSpinnerSP;
    private javax.swing.ButtonGroup groupeDroitModifSP;
    private javax.swing.ButtonGroup groupeDroitSP;
    private javax.swing.ButtonGroup groupeEtatModifSP;
    private javax.swing.ButtonGroup groupeEtatSP;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listeSallesSP;
    private javax.swing.JButton modifierCapaciteSP;
    private javax.swing.JPanel paneAjouterSalleSP;
    private javax.swing.JPanel paneAjouterSiteSP;
    private javax.swing.JSplitPane paneGererCoursSP;
    private javax.swing.JPanel paneGererSiteSP;
    private javax.swing.JScrollPane paneListeSallesSP;
    private javax.swing.JPanel paneSitesSP;
    private javax.swing.JLabel salleAddSP;
    private javax.swing.JLabel salleSP;
    private javax.swing.JTextField salleTFSP;
    private javax.swing.JComboBox<String> selectionnerSiteSP;
    private javax.swing.JComboBox<String> selectionnerSiteSP2;
    private javax.swing.JLabel siteAddSP;
    private javax.swing.JLabel siteSP;
    private javax.swing.JLabel siteSalleSP;
    private javax.swing.JTextField siteTFSP;
    private javax.swing.JButton supprimerSalleSP;
    private javax.swing.JButton supprimerSiteSP;
    private javax.swing.JTabbedPane tabbedPaneServicePlanification;
    private javax.swing.JButton validerSalleSP;
    private javax.swing.JButton validerSiteSP;
    // End of variables declaration//GEN-END:variables
}
